spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Bank
    username: postgres
    password: pgadmin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate


